# Generated by Django 4.0.2 on 2022-02-01 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='dayly_rate',
            new_name='daily_rate',
        ),
    ]
